### ISSUE TITLE
Stuck with beatsaber

### ISSUE THREAD

**Issue by F4LL3Notg** [hdgamer1404Jonas/WeebSaber#1]
After you stop the mod or delete it with appversionswitcher it stays on and you cant remove it

**Comment by hdgamer1404Jonas** [comment]
That is an issue of QAVS then, not my mod

Am Fr., 1. März 2024 um 19:51 Uhr schrieb F4LL3Notg <
***@***.***>:

**Comment by Rishphish** [comment]
I also have this problem. What was your soultion to this?
